sudo: required
language: php
dist: trusty

matrix:
  include:
  - php: '5.4'
    env: PHPUNIT_VERSION="4"
  - php: '5.5'
    env: PHPUNIT_VERSION="4"
  - php: '5.6'
    env: PHPUNIT_VERSION="5"
  - php: '7.0'
  - php: '7.1'
  - php: '7.2'
  - php: '7.3'

before_script:
  - if [[ $PHPUNIT_VERSION ]]; then
      curl -sSfL -o ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-$PHPUNIT_VERSION.phar;
    fi
  - date
  - env
  - uname -a
  - ulimit -a
  - ls -al
  - pwd
  - php -v
  - php -m
  - php --ri pdo;

script:
  - composer install-test-no-dev
